const PRODUCT_ONE = 'p1';
const PRODUCT_TWO = 'p2';
const PRODUCT_THREE = 'p3';
const PRODUCT_FOUR = 'p4';
const PRODUCT_FIVE = 'p5';

const TUESDAY = 2;

const TEN_PERCENT = 10 / 100;
const FIFTEEN_PERCENT = 15 / 100;
const TWENTY_PERCENT = 20 / 100;
const FIVE_PERCENT = 5 / 100;
const TWENTY_FIVE_PERCENT = 25 / 100;
const EIGHTY_PERCENT = 80 / 100;
const NINETY_PERCENT = 90 / 100;

const DISCOUNT_STANDARD_COUNT = 10;

const VOLUME_ORDER_COUNT = 30;

const STOCK_WARNING_THRESHOLD = 5;

const LIGHTNING_DELAY_MIN = 1000; // 1초

const LIGHTNING_ALERT_INTERVAL = 30000; // 30초

const DISCOUNT_ALERT_INTERVAL = 60000; // 1분
const DISCOUNT_DELAY_MIN = 20000; // 20초

const STOCK_LIMIT_WARNING = 50; // 재고가 50개 때 품절 표시

const POINTS_PER_ITEM = 1000; // 1000원당 1포인트 적립

const KEYBOARD_MOUSE_BONUS = 50; // 키보드와 마우스 구매 시 추가 포인트
const KEYBOARD_MOUSE_ARM_BONUS = 100; // 키보드, 마우스, 모니터암 구매 시 추가 포인트
const ITEM_COUNT_BONUS = {
  10: 20, // 10개 이상 구매 시 20포인트
  20: 50, // 20개 이상 구매 시 50포인트
  30: 100, // 30개 이상 구매 시 100포인트
};

export {
  PRODUCT_ONE,
  PRODUCT_TWO,
  PRODUCT_THREE,
  PRODUCT_FOUR,
  PRODUCT_FIVE,
  TUESDAY,
  TEN_PERCENT,
  FIFTEEN_PERCENT,
  TWENTY_PERCENT,
  FIVE_PERCENT,
  TWENTY_FIVE_PERCENT,
  EIGHTY_PERCENT,
  NINETY_PERCENT,
  DISCOUNT_STANDARD_COUNT,
  VOLUME_ORDER_COUNT,
  STOCK_WARNING_THRESHOLD,
  LIGHTNING_DELAY_MIN,
  LIGHTNING_ALERT_INTERVAL,
  DISCOUNT_ALERT_INTERVAL,
  DISCOUNT_DELAY_MIN,
  STOCK_LIMIT_WARNING,
  POINTS_PER_ITEM,
  KEYBOARD_MOUSE_BONUS,
  KEYBOARD_MOUSE_ARM_BONUS,
  ITEM_COUNT_BONUS,
};
