const PRODUCT_ONE = "p1";
const PRODUCT_TWO = "p2";
const PRODUCT_THREE = "p3";
const PRODUCT_FOUR = "p4";
const PRODUCT_FIVE = `p5`;

const DISCOUNT_RATE = {
  [PRODUCT_ONE]: 10 / 100,
  [PRODUCT_TWO]: 15 / 100,
  [PRODUCT_THREE]: 20 / 100,
  [PRODUCT_FOUR]: 5 / 100,
  [PRODUCT_FIVE]: 25 / 100,
};

export {
  PRODUCT_ONE,
  PRODUCT_TWO,
  PRODUCT_THREE,
  PRODUCT_FOUR,
  PRODUCT_FIVE,
  DISCOUNT_RATE,
};
