export const ITEM_LOW_STOCK_THRESHOLD = 5;

export const TOTAL_LOW_STOCK_THRESHOLD = 50;

export const DISCOUNT_ITEM_BULK_THRESHOLD = 10;

export const DISCOUNT_TOTAL_BULK_THRESHOLD = 30;

export const BONUS_POINTS_TOTAL_BULK_30_THRESHOLD = 30;

export const BONUS_POINTS_TOTAL_BULK_20_THRESHOLD = 20;

export const BONUS_POINTS_TOTAL_BULK_10_THRESHOLD = 10;
